Updated utils.jl to include checkPermissions() and fix checkFolder()
legend-exp/Juleana.jl pull request #35
Opened 2023-03-14 20:27 UTC by dcschaper

Calls to checkFolder() were failing before under the edge case that the folder specified did not exist, the user wanted to create it, but did NOT have write permission in the target directory. Added in a checkPermissions() function to utils.jl and then included this function in the checkFolder() function.

2023-03-14 20:55 UTC, oschulz requested changes

2023-03-14 20:55 UTC, oschulz commented on utils/utils.jl
> +                println("Create folder $folder")
Use

```julia
@info "Create folder $folder"
```

instead of `println` (except where a program produces it's actual output on the console). If it's output only relevant for debugging, use `@debug ...` instead of `@info ..`.

2023-03-14 20:55 UTC, oschulz commented on utils/utils.jl
> +    # Inside of this function, 'path' needs to be a string here because we are using ccall. First check if the input 'path' is of type PosixPath
Try using `uperm(filename)` instead of `ccall` - would probably be better cross-platform.

2023-03-14 21:27 UTC, dcschaper commented on utils/utils.jl
> +    # Inside of this function, 'path' needs to be a string here because we are using ccall. First check if the input 'path' is of type PosixPath
I agree with you that `ccall` might not be great cross-platform, but I don't think `uperm()` is the correct function since it returns the permissions of the OWNER of the file (see docs at https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.uperm) and not the specific user who is querying the permissions. The other options are `gperm` and `operm` for group and not-the-owner-and-not-in-the-group cases, but I thought that, for example, using `operm` could possibly return an edge case if the situation where the querying user was NOT the owner of a file/directory, but WAS in a group with control over it. `ccall` was at least returning the expected values. I agree, we should find a more elegant solution in the future.

2023-03-15 08:52 UTC, oschulz commented on utils/utils.jl
> +    # Inside of this function, 'path' needs to be a string here because we are using ccall. First check if the input 'path' is of type PosixPath
You're right, we can't use `uperm` here, let's stick with your solution for now.

2023-03-16 17:48 UTC, merged