LQ example script for one period of one detector
legend-exp/Juleana.jl pull request #47
Opened 2024-06-13 12:03 UTC by DaGeibl

Example script of how to LQ in the dataflow. Unnecessary plots and unused code snippets can be removed. Compare to more stripped down version in "LegendSpecFits" pull request

2024-10-04 14:50 UTC, DaGeibl commented
first version of lq processor for one run

2024-10-07 09:17 UTC, theHenks requested changes

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +
I need here the config parameters which should go into the metadata.

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +        lq_modes = [Symbol("gaussian"), Symbol("percentile")] # In ein config file auslagern
What is the different between these modes? Can they be configured in the function?

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +            table = data[ch].dataQC[:]
You can use the `read_ldata` function from `LegendDataManagement`

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +            f_cal = ljl_propfunc(pd[det].e_cusp_ctc.cal.func)
For all of this there is an automatic calibration function in `LegendEventAnalysis` . The other processors are using them already, so you can have a look there.

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                    drift_result, drift_report = lq_drift_time_correction(lq_e_corr, qdrift, e_cal, DEP_µ, DEP_σ;e_expression="e_cusp", mode=lq_mode)
Isn't there first an energy correction going on? Even if it is at the moment just `LQ/e` I would still make a separate function similar to the `A/E` . In a second step the drift time correction can be applied.

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                #Für den plot brauch ich die daten auf den DEP gecutted, bin mir unsicher wo genau ich das hinpacken soll. Also die daten zuschneiden hier im processor, oder das plotten in der functi
This should best go into the report from the drift time correction. Then you can write a recipe for the plot here.

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                left_margin = -15Plots.mm, bottom_margin = -13Plots.mm, c=:viridis, fontfamily="Computer Modern", formatter=:plain, thickness_scaling=3, size=(1200,900))
- The font `ComputerModern` sometimes throws an error. I would go with something else or just the default here.
- Is that much margin necessary? Plots is sometimes so weird...

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                savefig(p, joinpath("/mnt/artemis02/users/gieb/MPP_Code/Documents/Plots/LQ_Processor_Test", "drift_time_vs_lq_plot.png"))
This needs to use the `savelfig` function

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                try
Same as above.

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                    result, report = LQ_cut(DEP_µ, DEP_σ, e_cal, lq_class)
The report should be plottable. So maybe we can move some of the plots to report and write a recipe.

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                histogram2d(e_cal, lq_class , xlabel="Energy", ylabel="LQ (A.U.)", title="LQ Cut for Detector: $det",
Move to recipe?

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                plot(h_diff, xlabel="Energy", ylabel="Counts", title="Energy of", framestyle=:box, fontfamily="Computer Modern", formatter=:plain, dpi=300, thickness_scaling=1.6, size=(1200,900),
What does this plot show?

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                @info("starting to calculate SF values")
Within the processor I would only use `@debug` for such things, otherwise the output is too big.

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +                final_result = (lq_cut_result = result, sf = sf_values)
Ist there the `func` and the `cut` value in there.? This is the most important since this is was the event level sees.

2024-10-07 09:17 UTC, theHenks commented on processors/a_process_lq.jl
> +
Here we need to merge the `PropDicts` first before doing the cut.

2024-10-11 18:07 UTC, closed without merging

2024-10-15 18:23 UTC, DaGeibl commented on processors/a_process_lq.jl
> +                plot(h_diff, xlabel="Energy", ylabel="Counts", title="Energy of", framestyle=:box, fontfamily="Computer Modern", formatter=:plain, dpi=300, thickness_scaling=1.6, size=(1200,900),
what percentage of events are cut by Lq for each energy bin