Updated LQ-processor
legend-exp/Juleana.jl pull request #64
Opened 2024-11-21 09:56 UTC by DaGeibl

Implements the run-wise LQ processor. The processor executes performs a simple energy correction, "lq_drift_time_correction", "LQ_cut" and a survival fraction calculation for some peaks and the Qbb region.

The function returns in its result:

- The result of "lq_drift_time_correction" which contains the function "func" that evaluates the lq-classifier, as well as "func_generic".
- The result of "LQ_Cut" which is the LQ-cut value
- The calculated survival fraction

Added the comments from the last pull request:

- updated how i read the data
- perform the energy correction in a additional step
- added information what needs to be put in the config file
- merge the PropDicts before the cut
- made nice plots and put them in a recipe

2024-12-11 12:05 UTC, fhagemann requested changes
Is this PR ready to be reviewed? It doesn't seem to be finished nor carefully checked for mistakes yet.

2024-12-11 12:05 UTC, fhagemann commented on processors/process_lq.jl
> +        qbb_pos = 2029.0u"keV"
This is not the correct `qbb` value in 76Ge: 2039keV..

2024-12-11 12:05 UTC, fhagemann commented on processors/process_lq.jl
> +        =#
What's up with this? This seems to be copied from the A/E processor?

2024-12-19 11:09 UTC, theHenks requested changes
Left some comments to the report log.

2024-12-19 11:09 UTC, theHenks commented on processors/process_lq_calibration_cut.jl
> +    log_nt_cut = NamedTuple{(:Channel, :Detector, :Status, Symbol("Classifier Type"), Symbol("LQ cut Value"), Symbol("Continuum SF"), Symbol("DEP SF"), :CutError)}
Is this `Symbol("Classifier Type")` needed?

2024-12-19 11:09 UTC, theHenks commented on processors/process_lq_calibration_cut.jl
> +    log_nt_cut = NamedTuple{(:Channel, :Detector, :Status, Symbol("Classifier Type"), Symbol("LQ cut Value"), Symbol("Continuum SF"), Symbol("DEP SF"), :CutError)}
If you want to already have it in place for different `classifier` types you should also include it in the `log_nt_cal`

2024-12-19 11:09 UTC, theHenks commented on processors/process_lq_calibration_cut.jl
> +                    log_info_dict[aoe_classifier] = log_info
Still using `aoe_classifier` variable.

2025-01-03 14:48 UTC, DaGeibl commented on processors/process_lq_calibration_cut.jl
> +                    log_info_dict[aoe_classifier] = log_info
fixed

2025-01-03 14:49 UTC, DaGeibl commented on processors/process_lq_calibration_cut.jl
> +    log_nt_cut = NamedTuple{(:Channel, :Detector, :Status, Symbol("Classifier Type"), Symbol("LQ cut Value"), Symbol("Continuum SF"), Symbol("DEP SF"), :CutError)}
I now already put the Sybol("classifier Type") in both logs to make them consistent

2025-02-14 10:52 UTC, DaGeibl commented
@theHenks , @fhagemann the pull request is finished from my side, and i would be happy if you could review it

2025-02-14 13:31 UTC, fhagemann requested changes

2025-02-14 13:31 UTC, fhagemann commented on config/processing_config.json
> +        "periods": [6,7,8,9],
Can someone comment on what effect it will have to change stuff in the `processing_config.json`?
Due to the whole merging, it is not easy to see whether this is a change from this PR or from some merge commits from some other PR (#78 ?).
It would be best, if (instead of merging), you would rebase your PR onto the current `main`, so that the changes we see are really just emerging from your proposals.

2025-02-14 13:31 UTC, fhagemann commented on src/log_texts.jl
> +"""
Is this still what we intend? I remember discussing that we should perform the fit without sideband subtraction by adding a constant term to the fit function (?)

2025-02-14 13:31 UTC, fhagemann commented on processors/process_lq_calibration_cut.jl
> +            dep_σ = mvalue(pars_energy[det].e_cusp_ctc.fit.Tl208DEP.fwhm / 2.355)
If we were to be super precise, it should be `2sqrt(2log(2))` instead of `2.355`.

2025-02-14 13:31 UTC, fhagemann commented on processors/process_lq_calibration_cut.jl
> +                    median_lq = median(filter(isfinite, lq_e_corr))
Could this be replaced by `LegendDSP.signalstats` or `LegendDSP.extremestats`?

2025-02-14 13:31 UTC, fhagemann commented on processors/process_lq_calibration_cut.jl
> +                    ctc_dep_edgesigma=ctc_dep_edgesigma, ctc_lq_precut_relative_cut=ctc_lq_precut_relative_cut, lq_outlier_sigma = lq_outlier_sigma, ctc_driftime_cutoff_method=ctc_driftime_cutoff_met
If you have keyword arguments that are called the same as the variables your passing, you can (after having a semicolon `;`) just replace `X=X` by just `X`.
Here, it would then be:
```julia
drift_result, drift_report = lq_ctc_correction(lq_e_corr, dt_eff, e_cal, dep_µ, dep_σ;
                    ctc_dep_edgesigma, ctc_lq_precut_relative_cut, lq_outlier_sigma, ctc_driftime_cutoff_method, dt_eff_outlier_sigma, lq_e_corr_expression, dt_eff_expression, ctc_dt_eff_low_quantile, ctc_dt_eff_high_quantile, pol_fit_order)
```
which would be much more compact to read.

2025-02-14 13:31 UTC, fhagemann commented on processors/process_lq_calibration_cut.jl
> +                savelfig(savefig, p, l200, filekey, det, Symbol("cut_fraction_$classifier"))
I remember your plots adding the `title` to both subplots, when you have residuals at the bottom.
To avoid this, you could do `plot!(title = "...", subplot = 1)` where applicable.

2025-02-14 13:31 UTC, fhagemann commented on processors/process_lq_calibration_cut.jl
> +                @debug("starting to calculate Total SF after lq and low AoE cut")
I would suggest a consistent naming `aoe`/`AoE` in the `@debug` messages.

2025-02-14 13:41 UTC, DaGeibl commented on src/log_texts.jl
> +"""
Generally yes, put this is something i did not implement yet

2025-02-14 13:43 UTC, DaGeibl commented on config/processing_config.json
> +        "periods": [6,7,8,9],
In genereal I think everyone wants to anyway modify their own processing config, to process what one needs. But i wanted to add the LQ-processor in the processing config, so everyone can acces it

2025-02-14 13:43 UTC, fhagemann commented on src/log_texts.jl
> +"""
So, what would be your plan on how to proceed: merge the PR in its current status and update that later in a separate PR or already implement and update that here?

2025-02-14 13:43 UTC, DaGeibl commented on processors/process_lq_calibration_cut.jl
> +                    median_lq = median(filter(isfinite, lq_e_corr))
Did not know that exists, i will have a look into that

2025-02-14 13:44 UTC, DaGeibl commented on processors/process_lq_calibration_cut.jl
> +                    ctc_dep_edgesigma=ctc_dep_edgesigma, ctc_lq_precut_relative_cut=ctc_lq_precut_relative_cut, lq_outlier_sigma = lq_outlier_sigma, ctc_driftime_cutoff_method=ctc_driftime_cutoff_met
thanks good to know

2025-02-14 13:52 UTC, DaGeibl commented on src/log_texts.jl
> +"""
So I wanted now change my focus on processing the Co-56 data so that Verena can start having a look at that, so it's second on my ToDo list. What would you suggest? merge like this and than make a new PR probably seems fine.

2025-02-14 14:40 UTC, DaGeibl commented on processors/process_lq_calibration_cut.jl
> +                    median_lq = median(filter(isfinite, lq_e_corr))
i mean i could use it for mean and std, but I would need to calculate the median this way. Is there an advantage to use signalstats over the function i already used?

2025-02-14 15:01 UTC, fhagemann commented on processors/process_lq_calibration_cut.jl
> +                    median_lq = median(filter(isfinite, lq_e_corr))
Signalstats and extremestats are allocation-free.

2025-02-14 16:14 UTC, DaGeibl commented on processors/process_lq_calibration_cut.jl
> +                    median_lq = median(filter(isfinite, lq_e_corr))
signalstats nimmt aber nur waveforms oder? also mit nem vector an floats gehts ned oder?

2025-02-14 16:22 UTC, fhagemann commented on processors/process_lq_calibration_cut.jl
> +                    median_lq = median(filter(isfinite, lq_e_corr))
Signalstats works with samples or waveform and can also be an array:
https://github.com/JuliaPhysics/RadiationDetectorDSP.jl/blob/main/src/signalstats.jl

2025-02-19 14:01 UTC, fhagemann commented on config/processing_config.json
> +        "periods": [6,7,8,9],
Then maybe remove the modifications that are not related to this PR (like this one).

2025-02-19 14:05 UTC, fhagemann commented on processors/p_process_lq_calibration_cut.jl
> +
Only the top plot needs `subplot = 1` for the title? The rest are not composite plots?

2025-02-19 14:21 UTC, DaGeibl commented on processors/p_process_lq_calibration_cut.jl
> +
yes

2025-02-19 14:55 UTC, fhagemann requested changes

2025-02-19 14:55 UTC, fhagemann commented on config/processing_config.json
> +        "process_sipm_thresholds_phy": {
With all the merges, this PR reintroduces stuff that should not be here (`process_sipm_thresholds_phy` was renamed on `main`).

I tried to clean up this commit history, please have a look at https://github.com/fhagemann/legend-julia-dataflow/commits/dev/

2025-02-19 15:24 UTC, fhagemann commented
This force push was done to clean the commit history and to rebase onto the current `main`.
Some of the issues arising from merging should hopefully be fixed now.

2025-02-19 17:20 UTC, fhagemann commented
@DaGeibl is there still something to be done from your side or is this ready to be reviewed/merged?

2025-02-19 17:23 UTC, DaGeibl commented
From my side it would be ready to be reviewed/merged.

2025-02-19 17:27 UTC, fhagemann commented
@DaGeibl Did you try whether this processor works when running the dataflow?
If so, I would be willing to merge.

2025-02-20 10:55 UTC, DaGeibl commented
I tested it, the processors are running

2025-02-21 19:14 UTC, theHenks approved these changes

2025-02-21 19:14 UTC, fhagemann approved these changes
Fine.

2025-02-21 19:15 UTC, merged